---
title: "WOODCARB3R Vignette"
author: "Ben Jones"
date: "`r Sys.Date()`"
bibliography: carb2.bib
output: bookdown::html_document2
vignette: >
  %\VignetteIndexEntry{Vignette Title} 
  %\VignetteEngine{knitr::rmarkdown} 
  \VignetteEncoding{UTF-8}
---

This package calculates estimates of the U.S. HWP contribution to annual greenhouse gas removals in the agriculture, forestry, land use, and land use change sector. The calculations are based on WOODCARB II as described in @skog_sequestration_2008. 

Final estimates can be calculated from several approaches, each using a slightly different method. Different approaches and the calculations can be found below. 


###Terms and Notation {-}


**Variable 1A**: $\Delta C_{IU\:DC}$ annual change in carbon stored in HWP in products in use where wood came from domestic consumption of products in the United States including imports, $Mg$ $C$ $yr^{-1}$.  

<br/>

**Variable 1B**: $\Delta C_{SWDS\:DC}$ annual change in carbon stored in HWP in products in SWDS (solid waste disposal sites) where wood came from domestic consumption of products in the U.S. including imports, $Mg$ $C$ $yr^{-1}$.  

<br/>

**Variable 2A**: $\Delta C_{IU\:DH}$ annual change in carbon stored in HWP in products in use where products came from domestic harvest in the U.S., $Mg$ $C$ $yr^{-1}$.  

<br/>

**Variable 2B**: $\Delta C_{SWDS\:DH}$ annual change in carbon stored in HWP in products in SWDS where products used wood from domestic harvest in the U.S., $Mg$ $C$ $yr^{-1}$.  


<br/>

Note:

$$\Delta C_{DC}  =  \Delta C_{IU\:DC} + \Delta C_{SWDS\:DC}$$  

$$\Delta C_{DH}  =  \Delta C_{IU\:DH} + \Delta C_{SWDS\:DH}$$   

These variables are estimates of annual changes in stock of HWP carbon. 

The HWP Variables 3, 4, and 5 are estimates of annual product imports and exports, as well as annual harvest for products. They are not pools of carbon.

###Estimating Variables 1A and 2A {-}

#####Annual change in C in products IU {-}



Estimate the change in carbon in products IU as:

\begin{equation}
C_{IU \: T_{i \: j}}(t)  = e^{-k_{T_j}(t-1900)}\times \text{Inflow}_{T_i}\times F_{T_{i \: j}}
(\#eq:one)
\end{equation}


\begin{equation}
C_{IU}(t)  =  \sum\limits_{T=1900}^t \sum\limits_{i=1}^n \sum\limits_{j=1}^m C_{IU \: T_{i \: j}}(t)
(\#eq:two)
\end{equation}

Estimate the change in carbon in products IU as:

\begin{equation}
\Delta C_{IU}(t)  =  C_{IU}(t) - C_{IU}(t-1)
(\#eq:three)
\end{equation}


Where:  

<br/>

  $t$ is the year for which annual change in HWP carbon stock is being estimated  
    

  $Inflow_{T_i}$ is the annual amount of carbon in primary product $\textit{i}$ that goes into products in use in year $\textit{T}$. Inflows are for years $T  =  1900$ to current year, $\textit{t}$. Inflow is subdivided into several primary products ($i  =  1 \: to \: n$), $Mg$ $yr^{-1}$. Inflow excludes an estimated loss/ discard as solidwood products are placed in end uses (McKeever 2004)  
    
  $T$ is the year when products initially go into the "products in use" pool 
    
  $i$ is the primary wood or paper product, $\textit{i}$ = 1 to $\textit{n}$ (defined below)
    

  $j$ is the end use for products, $j = 1$ to $m$ (defined below)
  
  $F_{T_{i\:j}}$ is the fraction of primary product $\textit{i}$ inflow in year $\textit{T}$ that goes into end use $\textit{j}$
  
  $k_{T_j}$ is the annual rate at which the products placed in end use $\textit{j}$ in year $\textit{T}$ go out of use. This is the annual rate at which the product is discarded from use. Discarded material may be recycled (including, for example, paper or chipping for mulch), burned, composted, or sent to SWDS. The rate may differ depending on the year products are placed in use, but is constant for the life of products placed in use in a particular year.
  
Note that: 

$$k_{T_j}=\frac{ln(2)}{HL_{T_j}}$$

Where ${HL_{T_j}}$ is the half-life in years for products placed in end use $j$ in year $T$. The half-life is the number of years it takes for half of the intial inflow amount to be discarded. 

$C(t)$ is the total carbon held in products in use, Mg. 

$\Delta C(t)$ is annual change in carbon in products in use between the end of year $t - 1$ and the end of year $t$, Mg $yr^{-1}$

<br/>

Primary products categories (labeled i) include three for solidwood products (lumber, structural panels and nonstructural panels) and one for all of paper and paperboard products. Lumber includes both hardwood and softwood lumber. Structural panels include softwood plywood and OSB. Nonstructural panels include hardwood plywood, particleboard, MDF, hardboard, and insulation board.

<br/>

End-use categories (labeled j) include four for solidwood products (single-family housing, multifamily housing, resi dential upkeep and improvement, and other uses) and one for all paper and paperboard uses. Other solidwood uses includes mobile homes, nonresidential construction, rail ties, rail cars, household furniture, commercial furniture, other manufacturing, shipping, and miscellaneous other.

<br/>
**Variable 2A**- Annual change in carbon held in products made from U.S.harvested wood (includes exports). 

Equations \@ref(eq:one)  through \@ref(eq:three) are used again to estimate annual carbon change in solidwood and paper products har- vested in the United States and stored in various end uses. 


The annual carbon inflow variables for solidwood and paper products are estimated using Equations \@ref(eq:four) and \@ref(eq:five), separately. The calculations are founded on the assumption that solidwood (or paper) products are all the same in the amount of roundwood used to make them in both the United States and in other countries where sawlogs or pulpwood may be exported and used to make products.


For solidwood products: 

\begin{equation}
\text{Inflow}_{T i} = P_{T  i} \:x \: \left[\frac{(SL_p - SL_{IM} + SL_{EX})}{SL_p}\right]
(\#eq:four)
\end{equation}

For paper and paperboard products:

\begin{align}
\text{Inflow}_T &= P_T \times (1-F_{nonwood\:fiber})\times(1-F_{woodpulp\:imp})\times\left[ \frac{(PW_p - PW_{IM} + PW_{EX})}{PW_p}\right]\\ 
&+ EX_{rec\:fiber\:pulp} + EX_{rec\:paper} + EX_{woodpulp}
(\#eq:five)
\end{align}
    

Where:
<br/>

$t$ is the year for which annual change in HWP carbon stock is being estimated  
    

$P_{T_i}$ OR $P_{T}$ is carbon in solidwood (4 products) or paper products (1 product), respectively, produced in the U.S. in year T. The time subscript, T, is omitted for most right-hand side variables to simplify the equations. 
    
  $SL_{P}$ is sawlogs used to make lumber, plywood, and miscellaneous products in the U.S. in year T, Mg $yr^{-1}$. 
    
 $SL_{IM}$ is sawlogs imported and used to make lumber, plywood, and miscellaneous products in the U.S. in year T, T, Mg $yr^{-1}$. 
 
  $SL_{EX}$ is sawlogs exported from the U.S. in year T, T, MG $yr^{-1}$. 
  
  $F_{nonwood\:fiber}$ is the fraction of total fiber used to make paper and paperboard that is nonwood fiber in year T.
  
  $F_{woodpulp\:imp}$ is the fraction of woodpulp used to make paper and paperboard imported to the U.S. in year T.
  
  $PW_{p}$ is pulpwood used to make paper and paperboard in the U.S. in year T, Mg $yr^{-1}$. 
  
  $PW_{IM}$ is pulpwood imported and used to make paper and paperboard in the United States in year T, MG $yr^{-1}$. 
  
  $PW_{EX}$ is pulpwood exported from the United States in year T, MG $yr^{-1}$.
  
  $EX_{rec\:fiber\:pulp}$ is carbon in recovered fiber pulp exported in year T, Mg $yr^{-1}$.
  
   $EX_{rec\:paper}$ is carbon in recovered paper exported in year T, Mg $yr^{-1}$.
   
  $EX_{woodpulp}$ is carbon in woodpulp exported in year T, Mg $yr^{-1}$.
  
<br/>    

Just as for _Variable 1A_, estimates of carbon stock change in _Variable 2A_ require data on product production in the U.S. back to 1900.     
  

Additionally, special data is needed on domestic roundwood harvest, imports and exports, and paper-related fiber imports and exports in order to calculate the ratios needed for Equations \@ref(eq:four) and \@ref(eq:five). Other parameters including factors to convert original product units to tons of carbon are the same as for Variable 1A. Specifically, the fractions of each product with various end uses ($F_{Ti\:j}$) and the half-life of products in end uses ($HL_{T\:j}$) are assumed to be the same as for _Variable 1A_. Which means that exported products (or logs and chips) are assumed to have end uses in the same proportions as in the United States, as well as the same half-life. 


###Estimating Variables 1B and 2B {-}
#####Annual change in carbon held in SWDS in the reporting country and annual change in carbon held in SWDS where wood came from harvest in the reporting country {-}

Estimates of annual change in carbon in "products in SWDS" for current year t for _Variables 1B and 2B_ may be obtained using Equations \@ref(eq:six) through \@ref(eq:ten), which are provided below. 

Solid-waste disposal sites include dumps, where oxygen is available to decompose all wood and paper over time, and landfills, where a covering is placed over waste periodically and oxygen is sealed out. With limited oxygen, a portion of wood and paper does not decay and will stay permanently in the landfill, and a portion is temporary and will be emitted as $CO_{2}$ to or $CH_{4}$ over time.

\begin{equation}
C_{SWDS\:PERM}(t)  =  \sum\limits_{T=1900}^t [D_{SWP}(T)] \times (1-F_{TO \: DUMPS}(T))
\times F_{SWP\:to \: SWDS}(T) \times (1- DOC_{F \: SWP}\times)
+ \sum\limits_{T=1900}^t [D_{PAPER}(T)]\times (1-F_{TO \: DUMPS}(T))
\times F_{PAPER \: to \: SWDS}(T) \times (1-DOC_{F \: PAPER})]
(\#eq:six)
\end{equation}


\begin{equation}
C_{SWDS\:TEMP}(t)  =  \sum\limits_{T=1900}^t e^{-k_{SWP \: DUMPS} \times (t-T)}
\times [D_{SWP}(T)\times F_{SWP \: to \: SWDS}(T)
\times F_{TO \: DUMPS}(T)]
+ \sum\limits_{T=1900}^t e^{-k_{SWP \: LF} \times (t-T)} \times [D_{SWP}(T)]
\times F_{SWP \: to \: SWDS}(T) \times (1-F_{TO \: DUMPS}(T))
\times DOC_{F \: SWP}] + \sum\limits_{T=1900}^t e^{-k_{PAPER \: DUMPS} \times (t-T)} \times [D_{PAPER}(T)
\times F_{PAPER to SWDS}(T) \times F_{TO \: DUMPS}(T)]
+ \sum\limits_{T=1900}^t e^{(-k_{PAPER \: LF} \times (t-T))}
\times [D_{PAPER}(T)\times F_{PAPER \: to \: SWDS}(T)
\times (1- F_{TO \: DUMPS}(T)) \times DOC_{F \: PAPER}]
(\#eq:seven)
\end{equation}


\begin{equation}
C_{SWDS}(t)  = C_{SWDS \: PERM}(t) + C_{SWDS \: TEMP}(t)

(\#eq:eight)
\end{equation}

\begin{equation}
\Delta C_{SWDS}(t) = C_{SWDS}(t)-C_{SWDS}(t-1)
(\#eq:nine)
\end{equation}

\begin{equation}
F_{X \: to \: SWDS}= 1- F_{X \: BURNED} - F_{X \: REC}- F_{X \: COMPOST},
(\#eq:ten)
\end{equation}

Where X is either SWP or PAPER.



Where:
<br/>

$t$ is current year (for year for which annual change in HWP carbon stock is being estimated). 
    
$T$ is the yar when the products are initially discarded and, in part, go into "products in SWDS" pool.
    
$D_{SWP}(t)$ is the amount of carbon discarded from solidwood products in use in year t, Mg $yr^{-1}$. 
    
$D_{PAPER}(t)$ is the amount of carbon discarded from paper products in use in year t,  Mg $yr^{-1}$. 
 
$F_{SWP\:to\:SWDS}(T)$ is the fraction of solidwood products discarded in year T that are sent to SWDS (includes dumps and landfills).
  
$F_{TO\:DUMPS}(T)$ is the fraction of solidwood and paper products that are discarded to SWDS that go to dumps rather than landfills in year T.
  
$F_{X\:BURNED}(T)$ is the fraction of products (X=SWP or paper) discarded in year T that are burned with or without energy production.
  
$F_{X\:REC}(T)$ is the fraction of products (X=SWP or paper) discarded in year T that are recovered for domestic recycling or for export.
  
$F_{X\:COMPOST}(T)$ is the fraction of products (X=SWP or paper) discarded in year T that are composted. 
  
$DOC_{F\:SWP}$ is the fraction of solidwood product carbon placed in SWDS that are landfills that is degradable (emitted to the atmosphere).
  
$DOC_{F\:PAPER}$ is the fraction of paper product carbon placed in SWDS that are landfills that is degradable. 
  
$C_{SWDS\:PERM}(t)$ is the total stock of carbon permanently stored in SWDS in year t. 
   
$k_{X\:Y}$ is the Annual rate at which the products placed in (y=) dumps or landfills emitted to the atmosphere. Where products are (x=) solidwood products (SWP) or paper. It is equal to ln(2)/HL, where HL is the half-life in years that HWP carbon is held in dumps or landfills before being emitted to the atmosphere.

$C_{SWDS\:TEMP}(t)$ is the total stock of carbon temporarily stored in SWDS in year t.

$\Delta C_{SWDS}$ is the annual change in carbon in products in SWDS between the end of year  $t - 1$ and the end of year $t$, Mg $yr^{-1}$

<br/> 
Notes on Equations:

* Equation \@ref(eq:six) estimates, for current year t, the total stock of solidwood and paper product carbon that is permanently stored in landfill SWDS. 
* Equation \@ref(eq:seven) estimates, for current year t, the stock of solidwood and paper product carbon that is temporarily stored in dumps or landfill SWDS. The rate of decay (or half-life) for the degradable carbon varies by product and type of SWDS (dumps or landfills).
* Equation \@ref(eq:nine) estimates, for current year t, the change in total carbon stock in products in SWDS. 

*Estimating Variable 1B- Annual change in carbon held in SWDS in the reporting country.* Variable 1B is estimated using equations \@ref(eq:six) through \@ref(eq:nine) where the variables $D_{SWP}(t)$ and $D_{PAPER}(t)$ are amounts of solidwood and paper products, respectively, that are discarded within the U.S. in year T. These are amounts that are discarded from products previously consumed in the U.S. 

<!---
talk about formulas, a5 sum up different approaches.  
--->

# References
